### ISSUE TITLE
[PROPOSAL] Hoplon 7.1

### ISSUE THREAD

**Issue by flyboarder** [hoplon/hoplon#184]
## Proposal ##
The following outlines recommendations for the next version of Hoplon.

Version 7.0 was an accumulation of all the changes that happened during the v6-alpha development cycle and made many breaking changes.

Version 7.1 attempts to provide 100% compatibility with 7.0 but also prepares the codebase for the next major version of clojure/clojurescript, and updates dependencies to the latest versions which changes browser compatibility, dropping older browsers and targeting evergreen-1 releases.

## Suggestions ##

- [x] Update Clojure to 1.9
- [x] Update ClojureScript to 1.9.660 via #187 
- [x] Update All Other Dependencies via #183 
- [x] Drop IE8 Support (via jQuery update)
- [x] Add Clojure Spec Support for macros #183 
- [x] Add Docstring and Pre/Post Condition Support to defelem via #181 
- [ ] ~~Move Protocols to Hoplon.protocol~~ Reorganize Core
- [x] Add Clojure Spec Support for elements/on!/do! via #185 
- [x] Enhance Attribute Changes post elem construction
 - [x] Enhance tests/spec's for macros/public functions

All of the above PR's are superseded by #199

**Comment by flyboarder** [comment]
IE Compatibility Note: As of April 2017 versions older than IE11 make up ~0.2 of web users, as per [W3C Browser Statistics](https://www.w3schools.com/Browsers/browsers_explorer.asp).

**Comment by alandipert** [comment]
👍  to dropping IE8.

I'm also a fan of everything else, except perhaps the Clojure 1.9 alpha upgrade. My only concern is needing to backpedal if they change it before 1.9 final is released, which seems like it could be Any Day Now ™️
